#ifndef LVGL_GLFW_DISPLAY_CONFIG_H
#define LVGL_GLFW_DISPLAY_CONFIG_H

#define LVGL_GLFW_LVGL_WIDTH 800
#define LVGL_GLFW_LVGL_HEIGHT 480
#define LVGL_GLFW_WINDOW_WIDTH 800
#define LVGL_GLFW_WINDOW_HEIGHT 480

#define LVGL_GLFW_PRESENTATION_MODE_STRETCH 0
#define LVGL_GLFW_PRESENTATION_MODE_PRESERVE_ASPECT_RATIO 1
#define LVGL_GLFW_PRESENTATION_MODE_FIXED_SIZE 2
#define LVGL_GLFW_PRESENTATION_MODE 0

#define LVGL_GLFW_SCREEN_SHAPE_RECTANGLE 0
#define LVGL_GLFW_SCREEN_SHAPE_ROUNDED 1
#define LVGL_GLFW_SCREEN_SHAPE_CIRCLE 2
#define LVGL_GLFW_SCREEN_SHAPE 0
#define LVGL_GLFW_CORNER_RADIUS 32

#define LVGL_GLFW_WINDOW_TITLE "LVGL Desktop Simulator"
#define LVGL_GLFW_ICON_PATH ""

#define LVGL_GLFW_OPENGL_MAJOR 3
#define LVGL_GLFW_OPENGL_MINOR 3
#define LVGL_GLFW_OPENGL_GLSL_VERSION "330"
#define LVGL_GLFW_OPENGL_CORE_PROFILE 1
#define LVGL_GLFW_WINDOW_RESIZABLE 1
#define LVGL_GLFW_WINDOW_VISIBLE 1
#define LVGL_GLFW_WINDOW_SCALE_TO_MONITOR 1
#define LVGL_GLFW_SWAP_INTERVAL 1
#define LVGL_GLFW_MAX_FPS 240
#define LVGL_GLFW_WINDOW_BACKGROUND_RED 0.08F
#define LVGL_GLFW_WINDOW_BACKGROUND_GREEN 0.08F
#define LVGL_GLFW_WINDOW_BACKGROUND_BLUE 0.10F

#endif
