#ifndef LVGL_GLFW_PROJECT_CONFIG_H
#define LVGL_GLFW_PROJECT_CONFIG_H

#define LVGL_GLFW_PROJECT_VERSION "0.7.2"

#define LVGL_GLFW_C_STANDARD 11
#define LVGL_GLFW_CXX_STANDARD 20

#define LVGL_GLFW_BUILD_SHARED_LIBS 0
#define LVGL_GLFW_GLFW_LIBRARY_TYPE "STATIC"
#define LVGL_GLFW_BUILD_GLFW_DOCS 0
#define LVGL_GLFW_BUILD_GLFW_TESTS 0
#define LVGL_GLFW_BUILD_GLFW_EXAMPLES 0
#define LVGL_GLFW_INSTALL_GLFW 0
#define LVGL_GLFW_BUILD_GLFW_X11 1
#define LVGL_GLFW_BUILD_GLFW_WAYLAND 1

#define LVGL_GLFW_USE_THORVG_INTERNAL 0

#define LVGL_GLFW_PREVIEW_INTERVAL_SECONDS 0.35

#endif
